### ISSUE TITLE
User Ränge

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.7#11]
Beim "User Ränge" editieren kommt 

Upps...

Entschuldige bitte! Das hätte nicht passieren dürfen. Wir kümmern uns so schnell wie möglich darum.

SQL-Debug:

#####################################################################
Datum = 09.02.15 09:28
URL = http://www.non-expendables.com/admin/?admin=positions&do=edit&id=5

MySQLi-Query failed:
ConnectErrorNo = 0
ConnectError =

QueryError = Unknown column 'color' in 'field list'

Query = SELECT `position`,`color` FROM `dzcp_positions` WHERE `id` = 5;
#####################################################################

Beim anlegen eines neuen Ranges will man eine Farbe festlegen - Die Farbauswahl Palette liegt über den Galeriebildern..

Klick mal auf "eitieren" kommt

Upps...

Entschuldige bitte! Das hätte nicht passieren dürfen. Wir kümmern uns so schnell wie möglich darum.

SQL-Debug:

#####################################################################
Datum = 09.02.15 09:31
URL = http://www.non-expendables.com/admin/?admin=positions&do=add

MySQLi-Query failed:
ConnectErrorNo = 0
ConnectError =

QueryError = Unknown column 'color' in 'field list'

Query = INSERT INTO dzcp_positions SET `pid` = '0', `position` = 'CoClanAdmin', `color` = '#ffff00';
#####################################################################

**Comment by hammermaps** [comment]
Bitte die DB neu installieren oder per Hand die Datenbank aktualisieren ->https://github.com/DZCP-Community/DZCP-1.7/blob/development/_installer/conf/mysql.php#L1980
sehe Zeile 1980

**Comment by 65DirtyHarry** [comment]
Thx.

Was hasts denn mit der UserRang Farbe aufsich ?

**Comment by hammermaps** [comment]
Kommt später im neuen Forum / Teams zum Einsatz,  Gruppenfarben halt, ist nur eine optische Geschichte.
