### ISSUE TITLE
Serverliste

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.7#14]
Will man einen neuen Server in der Serverliste anlegen kommt - Das Rechenergebnis vom Sicherheitscode ist nicht richtig!

Sicherheitescode wird auch nicht angezeigt

**Comment by hammermaps** [comment]
Schaue ich mir an, TPL 1.5 und 1.6?

**Comment by 65DirtyHarry** [comment]
1.5 OK
1.6 OK

1.7 !

**Comment by hammermaps** [comment]
Meine die Templates der 1.7

**Comment by 65DirtyHarry** [comment]
Sry, nur mit der 1.6 probiert

**Comment by hammermaps** [comment]
Meinst du einsenden neuer Server?
http://dzcp-beta.hammermaps.de/serverliste/
das geht
