### ISSUE TITLE
Teamlogo

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.7#15]
Wird ein Teamlogo hochgeladen was (teils) Tranzparent ist wird diese Tranzparenz in der TopMatchBox nicht angezeigt - Getestet mit png & gif

In beiden Templates

**Comment by acecom** [comment]
link zu dem logo in png und gif pls

**Comment by 65DirtyHarry** [comment]
Kann leider keine 2 links vom Tablet einfügen. 
http://non-expendables.com
TopMatch Box

**Comment by hammermaps** [comment]
https://github.com/DZCP-Community/DZCP-1.7/commit/429b00303e142ea47367fd559964a7174ef4e420
Probier die mal, weis nicht ob es geht, ist halt ein Versuch.
Bitte die Daten mit _minimize_ im text löschen, finden sich bei inc\images\clanwars\*

**Comment by 65DirtyHarry** [comment]
Nein, geht immernoch nicht

**Comment by 65DirtyHarry** [comment]
Gerade nochmal geschaut - Jetzt ists Logo in der Box tranzparent
