### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.7#16]

**Comment by acecom** [comment]
Der Status Aktiv oder Inaktiv hat nur Auswirkung auf die Formulare Fight Us oder Join Us. Bei Inaktive wird das Team in den Formularen nicht aufgeführt! Um ein neues Team anzeigen zulassen musst du die Option (beim neu erstellen oder editieren) Team-Show auf Anzeigen setzen.
