### ISSUE TITLE
Shoutbox Captcha

### ISSUE THREAD

**Issue by WuChEn** [DZCP-Community/DZCP-1.7#19]
Das Captcha bei der Shoutbox wird nicht geladen.
Getestet mit FF und GC.
Kann dies jemand bestätigen?

Gruß WU

**Comment by hammermaps** [comment]
Wenn der Shoutbox Captcha geht, geht der Login Captcha nicht mehr und umgekert.

**Comment by WuChEn** [comment]
Irgendwas wird da durcheinander geschmissen.
Die Soundausgabe bei der Shoutbox gibt das Ergebniss der Falschen Aufgabe im Login an.
Die Soundausgabe bei kommentaren und Login gibt das richtige Ergebniss zur eigentlichen Aufgabe wieder.

**Comment by hammermaps** [comment]
https://github.com/DZCP-Community/DZCP-1.7/commit/3f5fb524f46b4adb2fd5888ad61bb7bac7c54264
