### ISSUE TITLE
Login Box Captcha

### ISSUE THREAD

**Issue by hammermaps** [DZCP-Community/DZCP-1.7#20]
Der Captcha-Code in der Login Box geht nicht

**Comment by WuChEn** [comment]
Die Sprachausgabe stimmt, jedoch nicht die Anzeige. ;)

**Comment by hammermaps** [comment]
https://github.com/DZCP-Community/DZCP-1.7/commit/3f5fb524f46b4adb2fd5888ad61bb7bac7c54264
