### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.7#22]
Gerade frisch installiert inkl. ganz frischer DB dann

--

Fatal error: Call to undefined function db() in /usr/www/users/nonfex/_installer/conf/mysql.php on line 16

**Comment by 65DirtyHarry** [comment]
Arrrrgh !!! hat sich erledigt :(

**Comment by hammermaps** [comment]
Die Version ist noch nicht gepüft, ob der installer noch geht, das kommt noch die Tage.

**Comment by 65DirtyHarry** [comment]
Arrrrgh !!! hat sich erledigt :(

**Comment by 65DirtyHarry** [comment]
Sry aber Fehler tritt weiterhin auf - gerade die neue von GitHub (ClanKasse) installiert und gleicher Fehler wie oben

**Comment by hammermaps** [comment]
https://github.com/DZCP-Community/DZCP-1.7/issues/26
