### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.7#29]
MoinMoin

Nach starten der update.php oder der install.php kommt

Fatal error: Uncaught exception 'Exception' with message 'Unexisting db-config default' in /usr/www/users/nonfex/inc/database.php:68 Stack trace: #0 /usr/www/users/nonfex/inc/common.php(52): database->getInstance() #1 /usr/www/users/nonfex/_installer/conf/mysql.php(9): include('/usr/www/users/...') #2 /usr/www/users/nonfex/_installer/update.php(25): require_once('/usr/www/users/...') #3 {main} thrown in /usr/www/users/nonfex/inc/database.php on line 68

Was bringt ein "Update autor() & autorcolerd()" wenns der installer und das Update nicht gehen ???

Die letzte Version die sich installieren/updaten lässt ist bei mir vom 11.2.

**Comment by hammermaps** [comment]
Rewrite SQL-Backend, not Use.
