### ISSUE TITLE
Gameserver

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/DZCP-1.7#8]
Ich habe die Daten von http://dzcp-beta.hammermaps.de übernommen um die Gameserver auf meiner 1.7 einzutragen - Bei Hammermaps wird alles korrekt angezeigt, bei mir jedoch nicht (Bsp. [WBKS] Gaming#01 - Metro - NoRules {3000T/NoobMagnet/AllWeapon})

Die Map (MP_Subway - mp_subway) ist vorhanden im Pfad /public_html/inc/images/maps/frostbite/bf3/bf3/conquestlarge

**Comment by hammermaps** [comment]
Wird der Server als offline angezeigt oder nur Bild?

**Comment by 65DirtyHarry** [comment]
Offline und keine Map.
Siehe non-expendables.com/server
Der CS:GO wird angezeigt, (On und mit Maps)die anderen nicht

**Comment by hammermaps** [comment]
Hast du mal bitte einen Demo Admin

**Comment by 65DirtyHarry** [comment]
Email ist raus

**Comment by hammermaps** [comment]
Sehr interessant....
kannst du bitte in der inc/config.php -> view_error_reporting auf true stellen.
Dann bitte noch in der inc/debugger.php -> show_gameserver_debug auf true.
Hoffe das er was ausspuckt, warum es bei dir nicht geht.

**Comment by hammermaps** [comment]
UDP Ports sind wahrscheinlich vom Webhoster blockiert.
